name: 'git-pr-release-slack'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gitPrRelease:
    name: git-pr-release-slack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Extract PR body
        id: extract_body
        run: |
          release=$(gh pr view ${{ github.event.pull_request.number }} --json body | jq .body | sed -E 's/([^#])##([^#])/\1|\2/g' | cut -d '|' -f 2)
          echo "release=${release}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              text: '<!here>\n${{ steps.repository.outputs.name }}をリリースします\n${{ github.event.pull_request.html_url }}\n```\n${{ steps.extract_body.outputs.release }}\n```'
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}